Corrected data file format and added data analysis code
bschmookler/beamtests_dd4hep pull request #2
Opened 2024-05-29 01:32 UTC by JiaJunHuang120000

2024-05-29 01:32 UTC, JiaJunHuang120000 commented
Added the analysis codes and changed the names of some data fomatting for the code to access.

2024-06-03 18:29 UTC, bschmookler commented on Sipm_RadTest/Davis/FlowerBoard/IV_PreIrradiation/Board62_1_IV_UTC_20240514__17_47.txt
Hi @JiaJunHuang120000. Why did you delete these pre-irradition FlowerBoard files and not replacing them wit other ones?

2024-06-03 18:34 UTC, bschmookler commented on Sipm_RadTest/FlowerBoard/Irradiated/Board62_1_IV_UTC_20240514__23_45.txt
Why do you want to move this out of the 'Davis' subfolder?

2024-06-03 18:39 UTC, bschmookler commented on Sipm_RadTest/Davis/S13_6050/IV_PreIrradiation/S13A10_IV_UTC_20240509__22_28.txt
Again, you delete this file but don't replace it with anything???

2024-06-03 18:40 UTC, bschmookler commented on Sipm_RadTest/JF_6015/Irradiated/6015_1_IV_UTC_20240516__01_37.txt
Same comment as above.

2024-06-03 18:46 UTC, bschmookler requested changes
Check comments.

2024-06-03 23:28 UTC, closed without merging